DROP DATABASE IF EXISTS homegrown_db;
CREATE DATABASE homegrown_db;
USE homegrown_db;

CREATE TABLE plants (
id INTEGER NOT NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
scientific_name VARCHAR (100) NOT NULL,
sunlight_care VARCHAR (30),
indoor BOOLEAN,
watering_tips VARCHAR (100),
PRIMARY KEY (id)
);

CREATE TABLE user (
id INTEGER NOT NULL AUTO_INCREMENT,
email VARCHAR (50) NOT NULL,
password VARCHAR (50) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE notes (
id INTEGER NOT NULL AUTO_INCREMENT,
note VARCHAR (10000) NOT NULL,
user_id INTEGER,
plants_id INTEGER,
FOREIGN KEY (user_id) REFERENCES user (id),
FOREIGN KEY (plants_id) REFERENCES plants (id),
PRIMARY KEY (id)
);
